### ISSUE TITLE
Feature Request: Prefix for sort titles

### ISSUE THREAD

**Issue by darkknight6722** [ShaneIsrael/plex-auto-genres#12]
Add a feature like `PLEX_COLLECTION_PREFIX` but for sort titles. So the genre collections will be together instead of getting mixed with other collections.

**Comment by ShaneIsrael** [comment]
If I can figure out how to modify the sort title with the python plex api it shouldn't be an issue. I'll look into this.

**Comment by ShaneIsrael** [comment]
It doesn't look like there is a super clean way to accomplish this. When I add a collection I don't have a link to that collection object so I can't update it at that point. I would need to have a separate function that grabs all of your collections and then edits them one by one. 

The problem with doing it that way is that there isn't a way to distinguish the genre collections from your own personally created collections unless there was a hard coded list of genre collection names to prefix. 

I don't want to hard code anything because if TMDB were to add a new genre or update their genres the tool wouldn't know about those updates and the code would need to be manually updated every time and users would have to know to pull down the changes. 
__________
The one possibility that I could add is an additional command similar to the `--set-posters` command that you could run. You would need to provide a list of the collection names that you want to have prefixed with your prefix character. 

So maybe something like this

```
PLEX_COLLECTION_SORT_PREFIX="*"
PLEX_COLLECTION_SORT_LIST="action,adventure,comedy,tv movies,family,etc,etc"
```
It would add the prefix to the sort title of any collections in that list whether they be genre collections the tool made or some other collection you made yourself.

**Comment by darkknight6722** [comment]
It looks good to me. Will it also be available in automate.py?

**Comment by ShaneIsrael** [comment]
@darkknight6722 I made a branch with the change. Please feel free to try it out before I merge it in. 

https://github.com/ShaneIsrael/plex-auto-genres/pull/13

You can download the zip at this url to test it out
https://github.com/ShaneIsrael/plex-auto-genres/tree/feature-collection-sorting

**Comment by darkknight6722** [comment]
Everything worked perfectly. Thank you.
